# Generated by Django 6.0.3 on 2026-03-24 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Remedy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symptom_english", models.CharField(max_length=255)),
                ("symptom_telugu", models.CharField(max_length=255)),
                ("symptom_hindi", models.CharField(max_length=255)),
                ("remedy_name", models.CharField(max_length=255)),
                ("ingredients", models.TextField()),
                ("preparation_steps", models.TextField()),
                ("relief_time", models.CharField(max_length=100)),
                ("remedy_type", models.CharField(max_length=100)),
                ("verified", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="SuggestedRemedy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symptom", models.CharField(max_length=255)),
                ("remedy_name", models.CharField(max_length=255)),
                ("ingredients", models.TextField()),
                ("preparation_steps", models.TextField()),
                ("language", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UnknownSymptom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symptom_text", models.CharField(max_length=255)),
                ("language", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField()),
                ("feedback_text", models.TextField()),
                ("language", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "remedy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="remedies.remedy",
                    ),
                ),
            ],
        ),
    ]
