# Generated by Django 4.2.29 on 2026-03-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remedies', '0002_alter_feedback_id_alter_remedy_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remedy',
            name='ingredients_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remedy',
            name='ingredients_te',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remedy',
            name='preparation_steps_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remedy',
            name='preparation_steps_te',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remedy',
            name='remedy_name_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remedy',
            name='remedy_name_te',
            field=models.TextField(blank=True, null=True),
        ),
    ]
